### ISSUE TITLE
Public data cannot be accessed in the  article of the "Transcriptome variation in human tissues revealed by long-read sequencing".

### ISSUE THREAD

**Issue by YFFFFFFFFFFFF** [LappalainenLab/lorals#6]
Hello,

I went through your recent article "Transcriptome variation in human tissues revealed by long-read sequencing". I would like to apply your analysis of the transcriptome to my data.
However, the publicly available data URL (https://github.com/LappalainenLab/lorals_paper_code/tree/master/data) in the original code sharing link (https://github.com/LappalainenLab/lorals_paper_code) in your article is no accessible.
Would you like to share this data again? Maybe this will help me understand the details of your analysis?

**Comment by DafniG** [comment]
Hi,
We could not share publicly the data necessary to re-run the analysis since it contains genetic information that needs explicit permissions. The data folder just points to how the directory should be organised. If you want access to the genetic data you would need to get explicit approval via dbgap. Other publicly available files can be found here: https://gtexportal.org/home/datasets. If you have specific questions on a script feel free to e-mail me, but I'll close this thread now as it not related to the software. 
Cheers!

**Comment by zhangjy859** [comment]
Hi @DafniG, 

Sorry for reopen this issue, We aslo have the same issue, we have been apporved for access phs000424.v9.p2 via dabgap, but 
It seems that we are still unable to find the raw sequencing data for this project. We tried searching the metadata in `phs000424.v9.p2` using sample names from publicly available expression data, such as "GTEX-13VXU-0011-R11b-SM-5BFQZ," but we couldn't find any matching results. Could we have made a mistake somewhere?

Thank you for your kindly help.

Regrads
